version: "3.5"

# this docker compose file is used for deployment

services:

  # define database container
  db:
    container_name: app_${APP_ENV}_db
    image: mysql:8.1.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=prestapoints
      - MYSQL_USER=prestapoints
      - MYSQL_PASSWORD=prestapoints
      - MYSQL_DATABASE=prestapoints
    volumes:
      - prestapoints-db:/var/lib/mysql
    networks:
      - appinternals

  # define backend container
  back:
    container_name: app_${APP_ENV}_back
    image: ${DOCKER_USER}/prestapoints-back:${DOCKER_IMAGE_TAG}
    restart: always
    depends_on:
      - db
    networks:
      appinternals:
        aliases:
          - back
  
  # define nginx + front container
  nginx:
    container_name: app_${APP_ENV}_front
    image: ${DOCKER_USER}/prestapoints-front:${DOCKER_IMAGE_TAG}
    depends_on:
      - back
    restart: always
    networks:
      - appinternals
    ports:
      - ${GATEWAY_PORT:-8005}:80

volumes:
  prestapoints-db:
    driver: local
networks:
  appinternals:
    # customize the actual network name depending on environment, so "prod" containers do not share network with "preprod" even on same machine / docker server 
    name: appinternals_${APP_ENV}